# Generated by Django 5.2.6 on 2025-09-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_amount', models.PositiveSmallIntegerField(verbose_name='Количество мест')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='Резерв')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
            },
        ),
    ]
