# Generated by Django 5.2.6 on 2025-09-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_reservation_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="client",
        ),
        migrations.RemoveField(
            model_name="table",
            name="is_reserved",
        ),
        migrations.AddField(
            model_name="reservation",
            name="client_name",
            field=models.CharField(
                default="Имя гостя", max_length=35, verbose_name="На чье имя бронь"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="client_phone_number",
            field=models.CharField(
                default="Телефон для связи", max_length=25, verbose_name="Телефон"
            ),
        ),
    ]
