# Generated by Django 5.2.6 on 2025-09-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_reservation_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="client_willing",
            field=models.TextField(blank=True, null=True, verbose_name="Пожелания"),
        ),
    ]
