# Generated by Django 5.2.6 on 2025-09-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_reservation_client_willing"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[("Действительна", "Действительна"), ("Закрыта", "Закрыта")],
                default="Актуальна",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
