# Generated by Django 5.2.6 on 2025-09-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_alter_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Открыта", "Открыта"),
                    ("Закрыта", "Закрыта"),
                    ("Отменена", "Отменена"),
                ],
                default="Открыта",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
