# Generated by Django 5.2.6 on 2025-09-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='epigraph',
            field=models.TextField(blank=True, null=True, verbose_name='Эпиграф'),
        ),
    ]
