# Generated by Django 5.2.6 on 2025-09-07 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_page_epigraph'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название ресторана')),
                ('epigraph', models.TextField(verbose_name='Эпиграф')),
                ('description', models.TextField(verbose_name='Описание ресторана')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Изображение ресторана')),
                ('services', models.TextField(verbose_name='Услуги ресторана')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
                ('country', models.CharField(blank=True, max_length=35, null=True, verbose_name='Страна')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес')),
                ('client_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('client_phone_number', models.CharField(max_length=25, verbose_name='Телефон')),
                ('client_message', models.TextField(verbose_name='Сообщение')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageCategory',
        ),
    ]
