# Generated by Django 5.2.6 on 2025-09-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_delete_page_delete_pagecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='client_message',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='client_phone_number',
        ),
    ]
